export {default as EditUser} from './Admin/EditUser'
export {default as AddUser} from './Admin/AddUser'
export {default as Home} from './Admin/Home'
export {default as User} from './Admin/User'
// auth screen 
export {default as RegisterScreen} from './Auth/RegisterScreen'
export {default as LoginScreen} from './Auth/LoginScreen'
export {default as ListTasks} from './Client/ListTasks'
export {default as Newtask} from './Client/NewTask'
export {default as updatedTask} from './Client/UpdateTask'
export {default as GeneratePassword} from './Auth/GeneratePassword'