import { Form } from 'react-bootstrap'

export {default as EditUser} from './Admin/EditUser'
export {default as AddUser} from './Admin/AddUser'
export {default as Users} from './Admin/Users'
export {default as User} from './Admin/User'
// auth screen 
export {default as RegisterScreen} from './Auth/RegisterScreen'
export {default as LoginScreen} from './Auth/LoginScreen'
export {default as ListTasks} from './Client/ListTasks'
export {default as DashboardClientScreen} from './Client/DashboardClient'
export {default as GeneratePassword} from './Auth/GeneratePassword'
export {default as AdminHome} from './Admin/AdminHome'
export {default as NewTask} from './Client/NewTask'
export {default as Profil} from './Client/Profil'